### ISSUE TITLE
Getting Error When using example (using my custom bare server)

### ISSUE THREAD

**Issue by illusionTBA** [tomphttp/bare-client#1]
As the title says I'm getting an ` Uncaught (in promise) TypeError: Failed to fetch `. My bare server in use: [bare-server](https://bare.illusionss.dev/)

My Code: 
```js
  const client = new BareClient('https://bare.illusionss.dev/');
  const bareFetch = async () => {
    const response = await client.fetch('https://www.google.com/');
    console.log(response.status, await response.text());
  };
```

![image](https://user-images.githubusercontent.com/97645434/184256285-373b2c89-e446-4ea6-be04-af5ee06b3b01.png)

**Comment by e9x** [comment]
For reference, this was a result of CORs not being omitted. Fixed in release 1.0.5
