### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by allmors** [tomphttp/bare-client#2]
Are there any usage examples? I don't understand how the client is used

**Comment by illusionTBA** [comment]
Look at the readme

**Comment by allmors** [comment]
> Look at the readme

I don't understand how this is used, I can understand how the server is used, but the naked client can't understand it

**Comment by e9x** [comment]
> > Look at the readme
> 
> I don't understand how this is used, I can understand how the server is used, but the naked client can't understand it

This library allows you to utilize the server you setup. Ultraviolet for example has it's own implementation of the bare client that allows it to connect to the bare server and utilize it. Think of the bare server as an OpenVPN server and the bare client as an interface for a user or script like OpenVPN GUI. This allows you to programmatically use the bare server.
