### ISSUE TITLE
error to run example code

### ISSUE THREAD

**Issue by erickythierry** [tomphttp/bare-client#7]
I'm trying to run this example code:

```
import { createBareClient } from '@tomphttp/bare-client';

/**
 * Fetch the manifest so client.fetch will be ready to execute immediately.
 */
const client = await createBareClient('http://localhost:8080/');

const response = await client.fetch('https://www.google.com/');

console.log(response.status, await response.text());
```

I installed `npm install @tomphttp/bare-server-node`
and ran this command in a separate console: `npx bare-server-node --port 8080 --host localhost`

I believe I started the server normally:
```
Error Logging: false
URL: http://localhost:8080/
Maintainer: undefined
```

however, when running the example code defining localhost as the server address, I received this error:

![image](https://github.com/tomphttp/bare-client/assets/11170366/75933970-0d35-4b17-9789-8abd76382c95)

Any help on how to make it work?

**Comment by illusionTBA** [comment]
its not meant for nodejs you need a websocket polyfill. i would give it to you but i completely lost that code a long time ago

**Comment by erickythierry** [comment]
> its not meant for nodejs you need a websocket polyfill. i would give it to you but i completely lost that code a long time ago

Thanks for the answer.
After a long search on this project, I ended up finding this lib:
https://www.npmjs.com/package/@nebula-services/bare-client

I managed to make it work with it, I believe it has been adapted to work with nodejs.
